<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'zend-view-helper/widget/bootstrap-alert'         => __DIR__ . '/view/zend-view-helper/widget/bootstrap-alert.phtml',
    'zend-view-helper/widget/bootstrap-form-checkbox' => __DIR__ . '/view/zend-view-helper/widget/bootstrap-form-submit.phtml',
    'zend-view-helper/widget/bootstrap-form-submit'   => __DIR__ . '/view/zend-view-helper/widget/bootstrap-form-submit.phtml',
    'zend-view-helper/widget/bootstrap-form-group'    => __DIR__ . '/view/zend-view-helper/widget/bootstrap-form-group.phtml',
);
