<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'travello-view-helper/widget/bootstrap-alert'         => __DIR__ . '/view/travello-view-helper/widget/bootstrap-alert.phtml',
    'travello-view-helper/widget/bootstrap-form-checkbox' => __DIR__ . '/view/travello-view-helper/widget/bootstrap-form-checkbox.phtml',
    'travello-view-helper/widget/bootstrap-form-submit'   => __DIR__ . '/view/travello-view-helper/widget/bootstrap-form-submit.phtml',
    'travello-view-helper/widget/bootstrap-form-group'    => __DIR__ . '/view/travello-view-helper/widget/bootstrap-form-group.phtml',
    'travello-view-helper/widget/bootstrap-form-static'   => __DIR__ . '/view/travello-view-helper/widget/bootstrap-form-static.phtml',
);
