<?php
/**
 * Zend Framework 3 module with a couple of useful view helper
 *
 * @package    ZendViewHelper
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/RalfEggert/zend-view-helper
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */
?>
<?php if ($this->element->getOption('heading')) : ?>
    <h4>
        <?php echo $this->translate(
            $this->element->getOption('heading')
        ) ?>
    </h4>
<?php endif; ?>
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <div class="checkbox">
            <label>
                <?php echo $this->formElement($this->element); ?>
                <?php echo $this->translate(
                    $this->element->getOption('label')
                ); ?>
            </label>
        </div>
    </div>
</div>
