<?php
/**
 * Zend Framework 3 module with a couple of useful view helper
 *
 * @package    TravelloViewHelper
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/RalfEggert/travello-view-helper
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */
?>
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php foreach ($this->submitElements as $element): ?>
            <?php echo $this->formElement($element); ?>
        <?php endforeach; ?>
    </div>
</div>
